"""
Compute Synergy-Redundancy Rank for GSM8K time series data.

This script processes 3 CSV files (al, ml, al+ml from GSM8K),
computes PhiID-based synergy and redundancy for time series data,
and generates Syn-Red Rank scores.

Input: Time series CSV files (512 steps)
Output: CSV files with Syn, Red, and ranks

Usage:
    python utils/compute_syn_red_rank.py
"""

import os
import pandas as pd
import numpy as np
from itertools import combinations
from tqdm import tqdm
from multiprocessing import Pool, cpu_count
import warnings

warnings.filterwarnings("ignore")

# ============================================================
# Configuration
# ============================================================
# 输入输出目录（可通过环境变量覆盖）
INPUT_DIR = os.environ.get("INPUT_DIR", "/data/zjj/Synergistic_Core/results/Qwen3_14B_Base/data")
OUTPUT_DIR = os.environ.get("OUTPUT_DIR", "/data/zjj/Synergistic_Core/results/Qwen3_14B_Base/data")

# File configurations
FILES_CONFIG = [
    {"name": "gsm8k_al", "type": "al", "per_head": True},
    {"name": "gsm8k_ml", "type": "ml", "per_head": False},
    {"name": "gsm8k_al_plus_ml", "type": "al_plus_ml", "per_head": False},
]

N_WORKERS = 16
USE_FAST_APPROXIMATION = False  # Use full PhiID calculation
MAX_QUESTIONS = 5  # Limit number of questions for quick testing (None for all)

# Path to effective lengths CSV (generated by 3_proxy_collection.py)
EFFECTIVE_LENGTHS_PATH = os.path.join(
    os.environ.get("OUTPUT_DIR", "/data/zjj/Synergistic_Core/results/Qwen3_14B_Base/data"),
    "L2_Norm",
    "gsm8k_effective_lengths.csv"
)

# ============================================================
# Import PhiID library
# ============================================================
try:
    from phyid.calculate import calc_PhiID
    print("Using full PhiID calculation")
except ImportError:
    print("Warning: phyid module not found. Please install integrated-info-decomp:")
    print("   pip install -e /path/to/integrated-info-decomp/")
    raise


# ============================================================
# Full PhiID Calculation
# ============================================================
def compute_single_pair(args):
    """Compute synergy/redundancy for a single component pair."""
    ts1, ts2 = args

    try:
        # Full PhiID calculation
        atoms_res, _ = calc_PhiID(ts1, ts2, tau=1, kind="gaussian", redundancy="MMI")

        # Average over time series
        syn_syn = float(np.nanmean(np.asarray(atoms_res["sts"])))
        red_red = float(np.nanmean(np.asarray(atoms_res["rtr"])))

        return syn_syn, red_red
    except Exception as e:
        return np.nan, np.nan


def compute_single_pair_wrapper(ts1, ts2, pair_idx):
    """Wrapper for multiprocessing."""
    syn, red = compute_single_pair((ts1, ts2))
    return (pair_idx, syn, red)


def _imap_task_helper(args):
    """Helper for imap_unordered to unpack tuple arguments."""
    return compute_single_pair_wrapper(*args)


def compute_syn_red_rank_for_file(csv_path: str, file_type: str, per_head: bool, output_path: str,
                                  effective_lengths_df: pd.DataFrame = None) -> None:
    """Compute Syn-Red Rank for a single CSV file.

    For each question, compute PhiID separately, then average syn/red values,
    then compute ranks.

    Args:
        csv_path: Path to input CSV file
        file_type: Type of component ('al', 'ml', 'al_plus_ml')
        per_head: If True, data is per-head
        output_path: Path to save output CSV
        effective_lengths_df: DataFrame with effective lengths per question
    """
    print(f"\n{'='*60}")
    print(f"Processing: {os.path.basename(csv_path)}")
    print(f"{'='*60}")

    # Load time series data
    df = pd.read_csv(csv_path)

    # Get step columns
    step_cols = [col for col in df.columns if col.startswith('step_')]
    num_steps = len(step_cols)
    print(f"Time series length: {num_steps} steps")

    # Create component identifier
    if per_head:
        df['component_uid'] = df['layer'].astype(str) + '_' + df['head'].astype(str)
    else:
        df['component_uid'] = df['layer'].astype(str)

    # Get unique questions and components
    if 'question_id' in df.columns:
        question_ids = df['question_id'].unique()
        if MAX_QUESTIONS is not None:
            question_ids = question_ids[:MAX_QUESTIONS]
        print(f"Questions: {len(question_ids)} (limited from {len(df['question_id'].unique())} total)" if MAX_QUESTIONS is not None else f"Questions: {len(question_ids)}")
    else:
        print("Warning: No question_id column found, treating all data as single question")
        question_ids = [0]

    unique_components = sorted(df['component_uid'].unique())
    print(f"Components: {len(unique_components)}")

    # Generate component pairs
    num_components = len(unique_components)
    component_pairs_list = list(combinations(unique_components, 2))
    num_pairs = len(component_pairs_list)
    print(f"Component pairs: {num_pairs}")

    # Initialize accumulators for averaging across questions
    pair_syn_accumulator = {pair: [] for pair in component_pairs_list}
    pair_red_accumulator = {pair: [] for pair in component_pairs_list}

    # Process each question separately
    print(f"Computing PhiID for each question separately...")
    for q_idx in tqdm(question_ids, desc="Processing questions"):
        # Filter data for this question
        q_df = df[df['question_id'] == q_idx] if 'question_id' in df.columns else df

        # Determine effective length for this question
        if effective_lengths_df is not None and 'question_id' in df.columns:
            effective_len_row = effective_lengths_df[effective_lengths_df['question_id'] == q_idx]
            if not effective_len_row.empty:
                effective_length = int(effective_len_row['effective_length'].values[0])
                # Limit to available steps
                effective_length = min(effective_length, num_steps)
            else:
                effective_length = num_steps
        else:
            effective_length = num_steps

        # Use only effective steps
        effective_step_cols = step_cols[:effective_length]

        # Pre-extract time series for each component
        ts_list = []
        for comp in unique_components:
            comp_df = q_df[q_df['component_uid'] == comp]
            if len(comp_df) > 0:
                ts = comp_df[effective_step_cols].values.flatten().astype(np.float64)
                ts_list.append(ts)
            else:
                # Component not found in this question, use zeros
                ts = np.zeros(len(effective_step_cols), dtype=np.float64)
                ts_list.append(ts)

        # Generate all pair computation tasks
        tasks = [(ts_list[i1], ts_list[i2], pair_idx)
                 for pair_idx, (i1, i2) in enumerate(combinations(range(num_components), 2))]

        # Multiprocess computation for this question with progress bar
        with Pool(N_WORKERS) as pool:
            results = list(tqdm(pool.imap_unordered(
                _imap_task_helper,
                tasks
            ), total=len(tasks), desc=f"Computing PhiID (Q{q_idx})", leave=False))

        # Store syn/red values for this question
        for pair_idx, syn, red in results:
            if pair_idx < len(component_pairs_list):
                pair = component_pairs_list[pair_idx]
                if not np.isnan(syn):
                    pair_syn_accumulator[pair].append(syn)
                if not np.isnan(red):
                    pair_red_accumulator[pair].append(red)

    print("Computation complete!")

    # Average syn/red values across all questions
    print("Averaging syn/red values across questions...")
    pair_metrics = {}
    for pair in component_pairs_list:
        syn_values = pair_syn_accumulator[pair]
        red_values = pair_red_accumulator[pair]
        if syn_values and red_values:
            avg_syn = np.mean(syn_values)
            avg_red = np.mean(red_values)
            pair_metrics[pair] = {'syn': avg_syn, 'red': avg_red}

    # Aggregate to single component level
    component_metrics = {comp: {'total_syn': 0.0, 'total_red': 0.0, 'count': 0}
                        for comp in unique_components}

    for (c1, c2), metrics in pair_metrics.items():
        for c in (c1, c2):
            component_metrics[c]['total_syn'] += metrics['syn']
            component_metrics[c]['total_red'] += metrics['red']
            component_metrics[c]['count'] += 1

    # Generate final component-level results
    final_component_data = []
    for comp, data in component_metrics.items():
        if data['count'] > 0:
            avg_syn = data['total_syn'] / data['count']
            avg_red = data['total_red'] / data['count']

            if per_head:
                layer, head = map(int, comp.split('_'))
                final_component_data.append({
                    'Layer': layer,
                    'Head': head,
                    'Syn': avg_syn,
                    'Red': avg_red
                })
            else:
                layer = int(comp)
                final_component_data.append({
                    'Layer': layer,
                    'Syn': avg_syn,
                    'Red': avg_red
                })

    result_df = pd.DataFrame(final_component_data)

    # Calculate Syn-Red difference, then rank
    result_df['Syn_Red_Diff'] = result_df['Syn'] - result_df['Red']
    result_df['Syn_Red_Rank'] = result_df['Syn_Red_Diff'].rank(method='dense')

    # Calculate syn_ratio and its rank
    result_df['syn_ratio'] = result_df['Syn'] / (result_df['Syn'] + result_df['Red'])
    result_df['syn_ratio_rank'] = result_df['syn_ratio'].rank(method='dense')
    # Center syn_ratio_rank around 0 (similar to Syn_Red_Rank)
    result_df['syn_ratio_rank_diff'] = result_df['syn_ratio_rank'] - result_df['syn_ratio_rank'].median()

    # Sort
    if per_head:
        result_df = result_df.sort_values(by=['Layer', 'Head'])
    else:
        result_df = result_df.sort_values(by=['Layer'])

    # Save results
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    result_df.to_csv(output_path, index=False)

    print(f"Results saved to: {output_path}")
    print(f"Processed {len(final_component_data)} components")


def main():
    """Main execution function."""
    print("=" * 60)
    print("GSM8K Syn-Red Rank Computation (Qwen3-14B-Base)")
    print("=" * 60)

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Load effective lengths if available
    effective_lengths_df = None
    if os.path.exists(EFFECTIVE_LENGTHS_PATH):
        effective_lengths_df = pd.read_csv(EFFECTIVE_LENGTHS_PATH)
        print(f"\nLoaded effective lengths from: {EFFECTIVE_LENGTHS_PATH}")
        print(f"  Questions: {len(effective_lengths_df)}")
        print(f"  Avg length: {effective_lengths_df['effective_length'].mean():.1f} steps")
        print(f"  Min/Max: {effective_lengths_df['effective_length'].min()} / {effective_lengths_df['effective_length'].max()} steps")
    else:
        print(f"\nWarning: Effective lengths file not found: {EFFECTIVE_LENGTHS_PATH}")
        print("  Using full time series (may include post-EOS padding)")

    # Process each file
    for config in FILES_CONFIG:
        file_name = config['name']
        file_type = config['type']
        per_head = config['per_head']

        # Build file paths
        input_path = os.path.join(INPUT_DIR, "L2_Norm", f"{file_name}.csv")
        output_path = os.path.join(OUTPUT_DIR, "L2_Norm", f"{file_name}_syn_red_rank.csv")

        # Check if input file exists
        if not os.path.exists(input_path):
            print(f"\nWarning: Input file not found: {input_path}")
            print(f"   Skipping...")
            continue

        # Compute syn-red rank for this file
        compute_syn_red_rank_for_file(
            input_path,
            file_type,
            per_head,
            output_path,
            effective_lengths_df=effective_lengths_df
        )

    print("\n" + "=" * 60)
    print("All computations complete!")
    print("=" * 60)
    print(f"\nOutput directory: {OUTPUT_DIR}")
    print("\nGenerated files:")
    for config in FILES_CONFIG:
        file_name = config['name']
        fname = f"{file_name}_syn_red_rank.csv"
        fpath = os.path.join(OUTPUT_DIR, fname)
        if os.path.exists(fpath):
            print(f"  - {fname}")
        else:
            print(f"  - {fname} (not found)")


if __name__ == "__main__":
    main()
